### ISSUE TITLE
Tips Page Bug

### ISSUE THREAD

**Issue by Shruti025** [skpandey885/HealhUb#100]
The Tips Page has responsiveness issues, I am attaching some screenshots for your reference.

![image](https://user-images.githubusercontent.com/72005584/156799986-e694c7d3-535c-4e83-a2ea-aaf173891fdb.png)
![image](https://user-images.githubusercontent.com/72005584/156800028-23aa0ab7-d602-4911-9b3f-75d230b1100c.png)
![image](https://user-images.githubusercontent.com/72005584/156800099-7bc73008-dd60-413b-8cf5-bf1ad932525f.png)

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by skpandey885** [comment]
@Shruti025 Whats the update? You have taken so much time for an Easy Issue? Create a PR by tonight.

**Comment by Shruti025** [comment]
sorry, got caught up with some college stuff. Will make a PR asap
