### ISSUE TITLE
Centering the footer About Us section for all pages

### ISSUE THREAD

**Issue by Shruti025** [skpandey885/HealhUb#101]
The About Us section is not centered correctly for all the Pages excluding Covid and looks like this

![image](https://user-images.githubusercontent.com/72005584/156802332-08361559-54fe-4aae-8331-5d3b4221f26f.png)

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by skpandey885** [comment]
Check the footer of all the pages of HealhUb and fix all of them. Make them to center.
