### ISSUE TITLE
Change design of landing page

### ISSUE THREAD

**Issue by Tess-Vanta** [skpandey885/HealhUb#102]
I would like to improve the design of landing page and also fix the some issues like text readability and horizontal scroll.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/72697074/156867635-59677533-735b-41aa-b562-ce1fad8e284c.png">

**Comment by skpandey885** [comment]
can you elaborate the issue

**Comment by Tess-Vanta** [comment]
Keeping the content same.. I want to optimize the design for more readable test and easy navigation and interactive landing page. Also I want to add the list of services provided by the site to the home page

**Comment by skpandey885** [comment]
Go ahead and make a PR. If I'll like the work I will merge it. Can't agree more.
