### ISSUE TITLE
Change the About Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#103]
**CURRENT BEHAVIOUR:** The current About Page is laggy. 
Link to about page: https://skpandey885.github.io/HealhUb/pages/about.html
**EXPECTED BEHAVIOUR:** Either improve the UX or Change the design of the whole page.

**Comment by ahmadjubair33** [comment]
Hi, @skpandey885 Please assign this issue to me. I have seen your about page and there are lots of faults. I will update the about page. Thanks

**Comment by skpandey885** [comment]
> Hi, @skpandey885 Please assign this issue to me. I have seen your about page and there are lots of faults. I will update the about page. Thanks

Go ahead. Must Go through the steps in Readme.MD before starting.

**Comment by skpandey885** [comment]
@ahmadjubair33 Whats the update??

**Comment by ahmadjubair33** [comment]
Hi @skpandey885 I have raised a Pr please review It.

**Comment by skpandey885** [comment]
@ahmadjubair33 Please check my comment on your PR.

**Comment by Shruti025** [comment]
Can I work on this under JWOC?
