### ISSUE TITLE
Fix the Responsivenes

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#104]
**Fix the Responsiveness of the Humburger Icon in the team page**
<img width="720" alt="Screenshot 2022-03-05 at 10 18 58 AM" src="https://user-images.githubusercontent.com/78532081/156868376-9d83ecde-73e8-4813-a497-52303749c4e1.png">

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by skpandey885** [comment]
> I want to work on this under JWOC

I guess you are already working on 2 issues. Finish them asap then i'll assign you.

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC

**Comment by Shruti025** [comment]
> I guess you are already working on 2 issues. Finish them asap then i'll assign you.

I have made a PR for one of them just now

**Comment by skpandey885** [comment]
@Tess-Vanta @Shruti025  First Come First serve :)
