### ISSUE TITLE
Text Issue in Tips Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#106]
**CURRENT BEHAVIOUR:** The text in the Tips page looks very bad on mobile view.

<img width="720" alt="Screenshot 2022-03-05 at 12 44 34 PM" src="https://user-images.githubusercontent.com/78532081/156873029-bec96581-7bc6-40ae-919f-723f6dea9e0f.png">
<img width="720" alt="Screenshot 2022-03-05 at 12 44 29 PM" src="https://user-images.githubusercontent.com/78532081/156873048-767ac412-cf99-43ca-bdf4-5496a9731456.png">

**EXPECTED BEHAVIOUR:** Improve the indentation and size of the text. Format the text according to the view.

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

go ahead
