### ISSUE TITLE
Add Margin

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#117]
CURRENT BEHAVIOUR: In the <a href="https://skpandey885.github.io/HealhUb/pages/covidSection.html">Covid</a> page. There is very less gap between the "Choose a country" field and the icons below.
EXPECTED BEHAVIOUR: Increase the margin between them.

<img width="1262" alt="Screenshot 2022-04-05 at 5 52 08 PM" src="https://user-images.githubusercontent.com/78532081/161752549-ee24fd75-75b3-41d4-bf04-27c7da2658d9.png">

**Comment by skpandey885** [comment]
@Pritam0077 Go for it. 
Refer to the steps given here in order to work on this issue 👇🏻
https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf

**Comment by Rupantar-Borphukan** [comment]
I have solved it but some errors are coming while adding git push origin master

**Comment by skpandey885** [comment]
> I have solved it but some errors are coming while adding git push origin master

Hey Buddy, This is not how things work 😊 In order to contribute to the issue, you need to comment on the issue and get yourself assigned by the mentor. Then you should follow some steps. Do not clone the repo directly. Please look into some other issues and then I will assign you.

**Comment by Rupantar-Borphukan** [comment]
Ok Sir, Actually I am new to this so don't know how it's works.

**Comment by skpandey885** [comment]
> Ok Sir, Actually I am new to this so don't know how it's works.

Yeah. brother i got it. You can work on this issue.👇🏻 Go and comment here so that i can assign you.
https://github.com/skpandey885/HealhUb/issues/118
