### ISSUE TITLE
Improve "About" Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#13]
**Current Behaviour:**  The "About" Page of our website has good UI but less content.

<img width="1329" alt="Screenshot 2022-02-01 at 12 24 42 PM" src="https://user-images.githubusercontent.com/78532081/151925340-bdca09a0-a2cc-436b-918d-b23aa39b338a.png">
<hr>

**Expected Behaviour:**  Add more content in each section inside the "About" page and improve UI of the page.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

Assigned.

**Comment by skpandey885** [comment]
@codervivek5  while adding the content to the sections. Make sure that there is **no grammatical mistake**.

**Comment by codervivek5** [comment]
Ok i will remind it very well

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
I need better improvements on this page, Vivek did up to his level but this page needs more improvements.

**Comment by codervivek5** [comment]
hey, @skpandey885  Tell me something. what we have to do to improve this page.

**Comment by skpandey885** [comment]
@codervivek5 more content and some minor CSS improvements. But I won't re-assign you. You can look for some other changes.

**Comment by skpandey885** [comment]
@codervivek5 After merging your pr, the changes are not reflecting on the website. What kind of PR did you make?

**Comment by aryankaushik-git** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

Go ahead.

**Comment by riiyaaa** [comment]
I would like to work on this issue under jwoc!

**Comment by codervivek5** [comment]
@skpandey885 I have added some content only in the about section.
