### ISSUE TITLE
DropDown nav for mobile devices

### ISSUE THREAD

**Issue by aksharma27** [skpandey885/HealhUb#130]
The home link is overriding the logo when in mobile view.
Also I would like to align the link to center when in mobile view.
![Screenshot (114)](https://user-images.githubusercontent.com/83135634/193441040-40099211-8b8b-417a-a391-2ec0435b464d.png)

**Comment by skpandey885** [comment]
Hey @aksharma27! Go ahead and work on this issue. But Must follow [these] (https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf) steps.

**Comment by hemantkumar76** [comment]
heyi i gonna want to work here

**Comment by skpandey885** [comment]
> heyi i gonna want to work here

Hey there, I really appreciate your enthusiasm to work on the issue, but I am following the first come first serve principle. Please visit the website and find bugs (if any) or features that your want to fix/add.

**Comment by skpandey885** [comment]
@aksharma27 Please, let me know what is the status!

**Comment by aksharma27** [comment]
Sorry, which status?

**Comment by skpandey885** [comment]
Please check my comments on your PR ASAP!
