### ISSUE TITLE
Improvements in Tips Page UI [Hacktoberfest]

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#131]
Current Behaviour: The [Tips](https://skpandey885.github.io/HealhUb/pages/tips.html) page UI is more colorful than required and not following the website theme.

Expected Behaviour: It should have a similar design to [Covid Page](https://skpandey885.github.io/HealhUb/pages/covidSection.html) & [Tools Page](https://skpandey885.github.io/HealhUb/pages/tools.html).  Modify the UI and Design of Tips page and make it similar to the design of the Covid Page & Tools Page

<h3>Design of Covid Page & Tools Page (follows a white theme and a banner)</h3>
<img width="1438" alt="Screenshot 2022-10-02 at 3 11 00 PM" src="https://user-images.githubusercontent.com/78532081/193447905-62c2419a-ebc5-4803-8dc3-29c766f11428.png">
<img width="1438" alt="Screenshot 2022-10-02 at 3 10 55 PM" src="https://user-images.githubusercontent.com/78532081/193447913-deda5959-8c83-4c7a-87f4-b9b0cc351924.png">
<br>
<h3>Design of Tips Page (follows a colorful theme)</h3>
<img width="1438" alt="Screenshot 2022-10-02 at 3 14 29 PM" src="https://user-images.githubusercontent.com/78532081/193448007-7e8c6418-a1b2-49e4-b41c-b21dc555c5f5.png">

**Comment by Srinja333** [comment]
i want to work on it , assign me

**Comment by skpandey885** [comment]
Hey @Srinja333! Good to see your enthusiasm to work on the project.
Yes, It understood the issue you raised, you can proceed ahead and work on it.
Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.

Happy Hacktoberfest!

**Comment by Srinja333** [comment]
i am new in github contribution i want to know how to run project in my computer, how to see changes of webpages by my web browser, please help

**Comment by Srinja333** [comment]
i cloned it, and also made branch

**Comment by skpandey885** [comment]
Please follow these steps -  https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf

**Comment by Srinja333** [comment]
when i chenged in my branch then how to see changes?

**Comment by Srinja333** [comment]
PS E:\pr\HealhUb> git remote add upstream https://github.com/skpandey885/HealhUb.git
error: remote upstream already exists.

**Comment by Srinja333** [comment]
i got it, started working on it you can believe me

**Comment by skpandey885** [comment]
> I have got it, started working on it , you can believe me

Ha, work on it! I am not assigning issue to anyone!

**Comment by skpandey885** [comment]
@Srinja333 What is the status of your work?

**Comment by skpandey885** [comment]
@sumitkr2000 Are you interested to work on it?

**Comment by sumitkr2000** [comment]
@skpandey885 I will be happy to work on this issue. Thank you for considering me for this.

**Comment by skpandey885** [comment]
Hey @sumitkr2000! Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.

Happy Hacktoberfest!
