### ISSUE TITLE
improvement in UI of bodyFat.html in navbar

### ISSUE THREAD

**Issue by aksharma27** [skpandey885/HealhUb#133]
I will change the navlinks button border to 2px i.e, neither too sharp nor too curved so, it will give a modern look. 
Also the logo is overlapped by the home link when in mobile view, I will remove the ovelap by adding some margin. 
Please assign me this issue.

**Comment by skpandey885** [comment]
Hey @aksharma27! Can you please share screenshots, so that i can understand your concern properly.

**Comment by aksharma27** [comment]
Before: The Home link when hovered was overlapping the logo in mobile and
the text was left aligned.
After: Home link is not overlapping the logo when hovered in mobile view
and here I have aligned the text to center

**Comment by skpandey885** [comment]
Okey @aksharma27! Go ahead and must follow [these](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf) steps.

**Comment by c99SRS** [comment]
Hi @aksharma27 please assign this to me

**Comment by raushankumarmishra** [comment]
@skpandey885  please assign me this issue
