### ISSUE TITLE
Improvement in UI and Fonts 

### ISSUE THREAD

**Issue by ManishMadan2882** [skpandey885/HealhUb#135]
Can I get this issue assigned under Hacktober'22 ?

**Comment by skpandey885** [comment]
Hey @ManishMadan2882! Can you please elaborate the issue?

**Comment by ManishMadan2882** [comment]
The text readability is low at some point where the bg-image opacity can be reduced
The Font style on the home page can be made better.

**Comment by skpandey885** [comment]
Okey Go Ahead!

**Comment by skpandey885** [comment]
Hey @ManishMadan2882 ! 
Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.

**Comment by skpandey885** [comment]
Hey @ManishMadan2882! What are the updates?
