### ISSUE TITLE
Add "Preloader" to the website

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#14]
**Preloader** is the animation that shows up before the website loads up.
For reference :  <a href= "https://www.youtube.com/results?search_query=preloader+for+website+ ">Click Here</a>

**Current Behaviour:** There is no preloader for the website.

**Expected Behaviour:** Add a preloader to the website. There should be the logo of HealhUb at the preload.  
Get the logo from here: 
```
https://github.com/skpandey885/HealhUb/blob/main/assets/logo.png
```

**Comment by Ankit62042** [comment]
I  want to work on this issue

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC

**Comment by Kaggrov** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue

Go ahead.

**Comment by skpandey885** [comment]
Hey @ZaidMujahid @Kaggrov . We are following the _First Come first serve_ basis. Visit the website and see what functionality you can improve and then create the issue.

**Comment by skpandey885** [comment]
@Ankit62042 What is the update?

**Comment by Ankit62042** [comment]
I'm Working on it !! Just give me some time till 12:00

**Comment by Ankit62042** [comment]
Hii, I shared a video on discord of pre-loader that I created

**Comment by skpandey885** [comment]
@Ankit62042 Where's the PR?

**Comment by Ankit62042** [comment]
PR Sent

**Comment by skpandey885** [comment]
@Ankit62042 The preloader is not working.

**Comment by skpandey885** [comment]
@ZaidMujahid Are you interested in taking up this issue?

**Comment by SabariGanesh-K** [comment]
@skpandey885 Can I try?

**Comment by skpandey885** [comment]
> @skpandey885 Can I try?

Go for it.
