### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by rsinghcodes** [skpandey885/HealhUb#141]
I want to add 404 page with well designed UI and with graphics or illustration and with some appropriate information like we should inform the user that he has jumped or redirected to wrong page or the page he is trying to find is not available.

Please assign it to me.

**Comment by skpandey885** [comment]
Hey @rsinghcodes, go for it!

**Comment by c99SRS** [comment]
HI @skpandey885 I want to add some nice error page. please assign it to me

**Comment by rsinghcodes** [comment]
> HI @skpandey885 I want to add some nice error page. please assign it to me

Hey @c99SRS, I have already raised PR for this issue (#148).
