### ISSUE TITLE
Image and Article link not working in cards.html

### ISSUE THREAD

**Issue by mgjain9871** [skpandey885/HealhUb#16]
In cards.html, two photos of the blogs and articles cards are not loading and the URL in the last card is also not working .

![image](https://user-images.githubusercontent.com/71882225/151956725-68b17c46-20ee-41e9-bd0c-4ac928b95cf3.png)

**Comment by mgjain9871** [comment]
I want to work on this issue under JWOC.

**Comment by ronitblenz** [comment]
Hey, I have worked on several hackathons and I want to work on this issue
Please let me in as an assignee
Thanks and Regards

**Comment by skpandey885** [comment]
@mgjain9871  Go ahead.

**Comment by skpandey885** [comment]
> Hey, I have worked on several hackathons and I want to work on this issue Please let me in as an assignee Thanks and Regards

Hey @ronitblenz , You can create an issue by yourself. Check out the website and create an issue if you think you can improve some functionalities.

**Comment by skpandey885** [comment]
hey @mgjain9871  do you want to work on issue #11 ???  Because this issue and issue #11 are similar.

**Comment by mgjain9871** [comment]
Cool, I can go with that issue then

**Comment by ronitblenz** [comment]
So, Should I work on this issue ?

**Comment by skpandey885** [comment]
> Cool, I can go with that issue then. PLease assign me issue #11 @skpandey885

Ok Done!

**Comment by skpandey885** [comment]
@mgjain9871 
Go to #11 and type "Interested"

**Comment by ronitblenz** [comment]
Hey, is @mgjain9871 working on it? Else I am ready to be an assignee

**Comment by mgjain9871** [comment]
Actually, i am working on issue #11 and that would be completed by next hour , and on completion of that issue, this issue would be automatically solved.
@skpandey885 i think you can close this issue, my work on another is issue is almost done and i have solved this error.

**Comment by ronitblenz** [comment]
No issues brother, Happy coding 👨🏻‍💻
