### ISSUE TITLE
A login page for the users

### ISSUE THREAD

**Issue by ankita-104** [skpandey885/HealhUb#162]

**Comment by skpandey885** [comment]
Hey @ankita-104! A Login page would also be needing a backend, which framework will you be using for the backend/database?

**Comment by skpandey885** [comment]
please, let me now then ill assign you!

**Comment by rishabhknowss** [comment]
please assign me the task

**Comment by ankita-104** [comment]
> please, let me now then ill assign you!

well..I want to contribute for the front end part of the login page using html,css,js

**Comment by Amisha2004** [comment]
Please assign me this task

**Comment by skpandey885** [comment]
> > please, let me now then ill assign you!
> 
> well..I want to contribute for the front end part of the login page using html,css,js

Hey, the login page without backend will look like a dummy website, if you can add a backend/dB maybe firebase (because it’s easy) then i can assign you the issue.

**Comment by Priyanshu-Mehra** [comment]
hey can you assign me this issue.I am comfortable with firebase

**Comment by Priyanshu-Mehra** [comment]
I want to contribute to this repo

**Comment by Rahulgarg01** [comment]
Hey I can Create a signup page for your website with Mailchimp's API serving as backend.
Mailchimp API will allow you to add email subscribers and manage your users easily.....
If you feel it would be helpful this way then kindly assign the task.

**Comment by skpandey885** [comment]
> Mailchimp API



> hey can you assign me this issue.I am comfortable with firebase

Go ahead!

**Comment by skpandey885** [comment]
Hey @Priyanshu-Mehra, I am closing this issue, because i will be implementing the Db with the help of NodeJS soon.
