### ISSUE TITLE
Improve the CSS of Covid Section Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#17]
**Current Behaviour:**  The CSS of the Covid section page needs to be improved. The UI currently is not good looking
**Images:** <br>
<img width="1395" alt="Screenshot 2022-02-01 at 9 16 13 PM" src="https://user-images.githubusercontent.com/78532081/152001333-ddb64932-d7dc-4fbc-afeb-89f2a8639636.png">
<img width="1395" alt="Screenshot 2022-02-01 at 9 16 20 PM" src="https://user-images.githubusercontent.com/78532081/152001390-e3157e21-0630-4f99-a534-a268b5c3323d.png">
<hr>

**Expected Behaviour:** There should be improvements in the CSS of Covid Section Page.

**Comment by soumali28** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

Go ahead.
