### ISSUE TITLE
Remove a button

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#20]
In the covid section page. This 👇🏻icon in the top-left corner is not looking good.

```
https://skpandey885.github.io/HealhUb/pages/covidSection.html
```
<img width="147" alt="Screenshot 2022-02-02 at 4 30 16 PM" src="https://user-images.githubusercontent.com/78532081/152141518-0af25d5d-2517-4ff8-9c47-78f3942c9978.png">

**Expected Behaviour:**  Remove this icon

**Comment by Amit91848** [comment]
Hi! Can I work on this?

**Comment by skpandey885** [comment]
Go ahead! @Amit91848

**Comment by sharma-02** [comment]
I want to work on this issue under JWOC.
