### ISSUE TITLE
Improve the Tips page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#21]
**Current Behaviour:**  The CSS of the tips page is not that good.
```
https://skpandey885.github.io/HealhUb/pages/tips.html
```

**Expected Behaviour:**  Improve the CSS of the Tips page and add more tips in it. 
(Note:  The CSS of the tips page needs to be very good)

**Comment by yeshwanth235** [comment]
I am interested in it, assign it to me.

**Comment by skpandey885** [comment]
@yeshwanth235 What is the status?
