### ISSUE TITLE
Add a "Tools" Section

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#25]
**Current Behaviour:** The navigation bar has a BMI section that re-directs the user to the BMI Calculator tool. 

<img width="280" alt="Screenshot 2022-02-04 at 1 33 58 AM" src="https://user-images.githubusercontent.com/78532081/152420128-fae46458-bf96-4425-8186-e469f83a0a7a.png">

**Expected behaviour/ Changes you need to make:** 
1. Replace the BMI in the navbar with "Tools"
2. Create a new page to which the "Tools" button will re-direct.
3. Inside that tool page, Use Bootstrap cards or cool square divs. In each card/div Mention tools like BMI section, Medical section, and some other section.
**(NOTE: Before Starting the work, Must reach out to me. I will be guiding you and tell you-- how you have to design this page )**

**Comment by Srijita-Mandal** [comment]
Hii, Can I work on this issue under JWoC?

**Comment by skpandey885** [comment]
Go ahead

**Comment by skpandey885** [comment]
@Srijita-Mandal What is the update??

**Comment by Srijita-Mandal** [comment]
I can complete it by today. Can you please share rest card contents, other than BMI?
