### ISSUE TITLE
Improve the Responsiveness of the "Blogs & Articles" Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#27]
**Current Behaviour:**
```
https://skpandey885.github.io/HealhUb/pages/cards.html
```
<img width="350" alt="Screenshot 2022-02-04 at 10 41 32 PM" src="https://user-images.githubusercontent.com/78532081/152572393-8c15abf5-2238-486f-b16f-39790712fe16.png">
<img width="355" alt="Screenshot 2022-02-04 at 10 41 48 PM" src="https://user-images.githubusercontent.com/78532081/152572443-48747ac2-3720-41cc-97d6-b2a623fccc6b.png">
 
<hr>

**Expected Behaviour:**
The screenshots below are the correct positions and there position is good in every page except "Blogs & article" page.
<img width="321" alt="Screenshot 2022-02-04 at 10 42 26 PM" src="https://user-images.githubusercontent.com/78532081/152572537-fb8bc70e-ee89-4426-bffd-5ebb9a877693.png">
<img width="325" alt="Screenshot 2022-02-04 at 10 42 47 PM" src="https://user-images.githubusercontent.com/78532081/152572590-01dbb7c3-6911-4e47-a114-5f3d626560b9.png">

**Comment by Tess-Vanta** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

Ok

**Comment by skpandey885** [comment]
@Tess-Vanta Really good job.
