### ISSUE TITLE
Change the Navbar design

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#30]
**Current Behaviour:** The design of the navbar of the "Covid" page is different from the design of other navbars.

<img width="1434" alt="Screenshot 2022-02-05 at 7 51 46 PM" src="https://user-images.githubusercontent.com/78532081/152645666-5a41cef4-4e63-405f-bd38-689bdbf31c02.png">
<hr>

**Expected Behaviour:** Change this navbar design like the navbar of other pages (Simply copy the navbar code of other page and replace it with the "Covid" page)

**Comment by Amit91848** [comment]
Can i work on this?

**Comment by skpandey885** [comment]
> Can i work on this?

Yes. Go ahead.

**Comment by skpandey885** [comment]
@Amit91848 What is the update?

**Comment by Amit91848** [comment]
I copy pasted the code but due to bg-dark class it gets the greyish background colour. So should I remove the class?

**Comment by skpandey885** [comment]
> I copy pasted the code but due to bg-dark class it gets the greyish background colour. So should I remove the class?

Ok. Do any change. but make the navbar as i have told you.

**Comment by ronitblenz** [comment]
Can I work on this issue, if no one is doing?
