### ISSUE TITLE
Changes under "Covid Section" page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#32]
**Expected Behaviour:** Put these section "dos" & don't in separate boxes and add CSS to the boxes.

<img width="1345" alt="Screenshot 2022-02-05 at 11 26 39 PM" src="https://user-images.githubusercontent.com/78532081/152653191-e88b13e7-bf42-44be-ac4b-0dbd90b1acce.png">
<hr>

**For Reference: https://skpandey885.github.io/HealhUb/pages/covidSection.html**

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.
