### ISSUE TITLE
Fix the "Tools" link

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#52]
**CURRENT BEHAVIOUR:** When you go to "Tools" page (<a href="https://skpandey885.github.io/HealhUb/pages/tools.html">Click here to go!</a>) and click on Tools on the Navbar. It Redirects you to BMI Page.
**EXPECTED BEHAVIOUR:**  It should redirect to itself. Fix this.
(Also fix all the "Tools" link issues in the website.)

**Comment by armaanbadhan** [comment]
id like to work on this issue under jwoc

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC.

Go for it.
