### ISSUE TITLE
Improve the Responsiveness of the Tools Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#53]
**CURRENT STATUS:**  The tools page is not responsive.

<img width="952" alt="Screenshot 2022-02-11 at 8 29 01 PM" src="https://user-images.githubusercontent.com/78532081/153614827-2742c5cd-cacd-41f5-8d7e-2552ce6839b3.png">

<h3>EXPECTED BEHAVIOUR: MAKE IT FULLY RESPONSIVE FOR ALL SCREEN SIZES.</h3>

**Comment by yeshwanth235** [comment]
Can u assign it to me

**Comment by skpandey885** [comment]
> Can u assign it to me, under JWOC

Go for it
