### ISSUE TITLE
Fix the Navbar Design of Tools Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#54]
**CURRENT BEHAVIOUR:**  The Navbar of Tools page is not like the navbars used in other pages of the website.

<img width="1427" alt="Screenshot 2022-02-11 at 8 31 30 PM" src="https://user-images.githubusercontent.com/78532081/153615205-46a39bec-e53e-40d3-9f96-18b354b1a594.png">

**EXPECTED BEHAVIOUR:**  Make the Navbar of "Tools" Page like this Navbar. (This is the Navbar of Home Page)
<img width="1427" alt="Screenshot 2022-02-11 at 8 32 17 PM" src="https://user-images.githubusercontent.com/78532081/153615312-36325f4a-4a4a-4715-8422-1e1b078a710b.png">

**Comment by Tess-Vanta** [comment]
I want to take this up under JWOC

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by skpandey885** [comment]
> 

@Tess-Vanta Go for it.

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC.

First come, first serve :)
