### ISSUE TITLE
Improve the Responsiveness of the Preloader

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#55]
**CURRENT BEHAVIOUR:** The preloader is not aligned at the center for different screen sizes. It is only aligned perfectly for desktop size.
<img width="1427" alt="Screenshot 2022-02-11 at 9 33 23 PM" src="https://user-images.githubusercontent.com/78532081/153625874-3bdf1f24-8c95-47ea-b7be-f7465f5affab.png">

**EXPECTED BEHAVIOUR:** Align it to the center for all devices and all screen sizes.

**Comment by Srijita-Mandal** [comment]
I want to work on this issue under JWoC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWoC

👍🏻
