### ISSUE TITLE
Improve the Responsiveness of the Covid Section

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#56]
Covid Page: https://skpandey885.github.io/HealhUb/pages/covidSection.html
**CURRENT BEHAVIOUR:** The COVID page is not responsive. 

<img width="940" alt="Screenshot 2022-02-11 at 9 37 22 PM" src="https://user-images.githubusercontent.com/78532081/153626409-cb1d19c2-ef04-43ed-96a5-161107a284bb.png">

**EXPECTED BEHAVIOUR:** Improve the responsiveness and make it responsive for all device screens.

**Comment by Mainakroy050** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

Go ahead.

**Comment by sayan404** [comment]
I want to work in this issue under JWOC .

**Comment by skpandey885** [comment]
@sayan404  Go ahead.

**Comment by 920DEV** [comment]
I want to work in this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work in this issue under JWOC

do you want to work on this issue?

**Comment by Shruti025** [comment]
Hey @skpandey885 can I work on this issue under JWOC? I have commented earlier as well

**Comment by skpandey885** [comment]
> Can I work on this issue under JWOC?

Do you want to work on this issue?

**Comment by Shruti025** [comment]
> Do you want to work on this issue?

Hey, I got assigned another issue so I'll be working on that first.

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC.

**Comment by skpandey885** [comment]
> I want to work on this under JWOC.

ok
