### ISSUE TITLE
Add Slide Down Animation

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#59]
<h3>Current Behaviour: The Home page directly appears after the preloader and there is no animation.</h3>

**Video:**

https://user-images.githubusercontent.com/78532081/153702092-e8417b82-495c-4d1d-8e5e-6cded2e31753.mov
<hr>

<h3>Expected Behaviour: Add a slide-down Animation like this 👇🏻</h3>

 **Video:**

https://user-images.githubusercontent.com/78532081/153702222-679edb24-43dc-40d2-bad4-5178eacba320.mov

**Comment by Anosh21** [comment]
Hey @skpandey885 , I would like to take up this issue under JWOC.

**Comment by skpandey885** [comment]
> Hey @skpandey885 , I would like to take up this issue under JWOC.

Go ahead.

**Comment by skpandey885** [comment]
@Anosh21  Please check my comment on your PR. Reply ASAP

**Comment by Srijita-Mandal** [comment]
can I work on this issue under jwoc?

**Comment by Shruti025** [comment]
Hey can I work on this issue under JWOC?

**Comment by skpandey885** [comment]
> can I work on this issue under jwoc?

go ahead
