### ISSUE TITLE
Create the "Medical Help" Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#60]
**Current Behaviour:** If you click on the "Medical help" button which is inside the "Tools" page. The Medical help button does not have any Page linked to it.
**Expected Behaviour:** Create a Medical help page. and Inside that page add different sections. In each section, You have to add the name of the disease- its medicines, its causes, its reasons, etc., and a lot of things.
**(MUST CONSULT TO ME BEFORE STARTING THE WORK. I WILL TELL YOU HOW TO DESIGN THAT PAGE AND HOW TO KEEP THE THINGS)**

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC.

Go ahead

**Comment by skpandey885** [comment]
It's been 2 Days. What's the update?
