### ISSUE TITLE
Create "Nearby Hospital" Page and Add Google Map API functionality

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#66]
**CURRENT BEHAVIOUR:** If you go to the <a href="https://skpandey885.github.io/HealhUb/pages/tools.html">Tools</a> page & click on "Nearby Hospitals" button. There is no page currently.
**EXPECTED BEHAVIOUR:** Create the Nearby Hospitals Page and add Google Maps API functionality which shows Nearby Hospitals Based on User's Location.

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

Go ahead.

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
@DarkFalc0n What is the Update?

**Comment by DarkFalc0n** [comment]
> @DarkFalc0n What is the Update?

I am done however there is one bug, I will be fixing it overnight, and will PR tomorrow.

**Comment by skpandey885** [comment]
> I want to work on this issue under JWOC

@03amir Are you interested in taking this issue?

**Comment by 03amir** [comment]
Yes. You can assign me.

**Comment by skpandey885** [comment]
@03amir What is the update?

**Comment by 03amir** [comment]
i am working on it

**Comment by Tess-Vanta** [comment]
I want to take this up under JWOC

**Comment by skpandey885** [comment]
Go ahead
