### ISSUE TITLE
Improve the UX of About Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#70]
**CURRENT BEHAVIOUR:** The UX of the "About" Page is not that Good. It is a bit laggy.
Refer to this: https://skpandey885.github.io/HealhUb/pages/about.html
**EXPECTED BEHAVIOUR:** Improve the UX of the "About" Page and Make it smoother.

**Comment by Amit91848** [comment]
Can i work on this?

**Comment by skpandey885** [comment]
Go ahead.

**Comment by skpandey885** [comment]
@Amit91848 What is the update? Create a PR by tonight. I have given you long time to fix the issue

**Comment by 920DEV** [comment]
i want to work on this

**Comment by skpandey885** [comment]
@920DEV Go ahead.

**Comment by skpandey885** [comment]
@920DEV What is the Update? Generate the PR by Tonight. You have already taken 2 Days.

**Comment by 920DEV** [comment]
i am on it bro. i am trying to complete it as soon as  possible.

**Comment by skpandey885** [comment]
> i am on it bro. i am trying to complete it as soon as possible.

Generate a PR by tonight. You have already taken 3 days buddy. We are not allowed to give more than 2 days for a medium level issue.
