### ISSUE TITLE
Add a "Trainer" page in the "Tools" section

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#71]
**CURRENT BEHAVIOUR:** As you can see the dummy cards below👇🏻.
<img width="1402" alt="Screenshot 2022-02-17 at 12 24 37 AM" src="https://user-images.githubusercontent.com/78532081/154335831-23ad6d7f-a57a-476a-8373-79985c4805b9.png">
EXPECTED BEHAVIOUR: Change one of them to "Trainer" and create a trainer page. That page should contain Some questions and depending upon the user's input the page will display the answers.
(I know It may sound confusing. So before starting the work Must reach out to me , so that i will tell you how to make  & design this page )

**Comment by Tess-Vanta** [comment]
I would like to take up this issue under JWOC

**Comment by skpandey885** [comment]
Go ahead.

**Comment by Tess-Vanta** [comment]
Sorry, I have been assigned two issues ;(

**Comment by skpandey885** [comment]
> Sorry, I have been assigned two issues ;(

So you can work in two issues. Right?

**Comment by Tess-Vanta** [comment]
> > Sorry, I have been assigned two issues ;(
> 
> So you can work in two issues. Right?

Apart from this

**Comment by Tess-Vanta** [comment]
I would like to take up this issue under JWOC

**Comment by skpandey885** [comment]
> I would like to take up this issue under JWOC

go ahead.
