### ISSUE TITLE
Compress the size of all background Images

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#8]
**Current Behaviour:** All the images used as background in the website are of high size and quality. Due to this, it takes a lot of time to load the background images of the website.

**Changes Required:** Compress the size of every background image and add them to the website. Remove the highly-sized Background Images.

**Comment by PranK14** [comment]
i would like to work on this inder jwoc

**Comment by skpandey885** [comment]
Go ahead!

**Comment by PranK14** [comment]
@skpandey885  just one thing do i have to reupload those images after compressing in assets branch ?

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
> @skpandey885 just one thing do i have to reupload those images after compressing in assets folder?

Yes. after compressing the images you have to add them in the assets folder with the same name as earlier. @PranK14

**Comment by PranK14** [comment]
ok i will get it done

**Comment by sayan404** [comment]
I want to work in this issue under JWOC.

**Comment by codervivek5** [comment]
I want to work in this issue under JWOC.
i can do it

**Comment by wasimreja** [comment]
@skpandey885 bhaiya I would like to work on this under JWoC.

**Comment by skpandey885** [comment]
> @skpandey885 bhaiya I would like to work on this under JWoC.

Go ahead.

**Comment by skpandey885** [comment]
> I want to work in this issue under JWOC.

Go ahead

**Comment by skpandey885** [comment]
Things are Happening according to First come first serve basis :)

**Comment by sayan404** [comment]
Ok I will creat a new branch for a new pr @skpandey885
