### ISSUE TITLE
Re-design the Covid Section with proper Responsiveness

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#80]
**CURRENT BEHAVIOUR:** The covid Page needs to be updated with improved responsiveness.
**EXPECTED BEHAVIOUR:** Re-design the whole page from scratch with proper responsiveness.

**Comment by skpandey885** [comment]
@Tess-Vanta Take this one.

**Comment by Tess-Vanta** [comment]
> @Tess-Vanta Take this one.

Yes I will take this up
