### ISSUE TITLE
Fix the size of the Cards in Covid Blogs page and add more cards

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#89]
**CURRENT BEHAVIOUR:** The size of cards in the covid blogs page are different from each other. And the number of cards are also less in the covid blogs page.
<img width="1440" alt="Screenshot 2022-03-02 at 8 51 04 AM" src="https://user-images.githubusercontent.com/78532081/156288768-b552f861-ac38-49c4-b593-18975290a1e2.png">
**EXPECTED BEHAVIOUR:** Fix the size of every card to a fixed size like <a href="https://skpandey885.github.io/HealhUb/pages/cards.html">this</a> page. Add more cards to it.

**Comment by yeshwanth235** [comment]
I would like to work on this issue

**Comment by skpandey885** [comment]
> I would like to work on this issue

Ok
