### ISSUE TITLE
Add CovidTracking API 

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#9]
**Current Behaviour:**  Inside the Covid Section (https://skpandey885.github.io/HealhUb/pages/covidSection.html) of our website. The covid tracking is not working.

<img width="1359" alt="Screenshot 2022-02-01 at 9 11 47 AM" src="https://user-images.githubusercontent.com/78532081/151909684-6bf364f0-1a64-4e46-9080-059e5a3538cf.png">

<hr>

**Expected Behaviour:** Add the proper live covid tracking functionality via apis.

**Comment by Atif0604** [comment]
i would like to work on this under JWOC
@skpandey885

**Comment by yeshwanth235** [comment]
I am also interested in taking this issue under JWOC

**Comment by skpandey885** [comment]
> i would like to work on this under JWOC @skpandey885

Go Ahead! @Atif0604

**Comment by skpandey885** [comment]
> I am also interested in taking this issue under JWOC

Hey, you can create any issue by yourself. Visit the website and see what improvements we can make and then create an issue :)

**Comment by skpandey885** [comment]
Hey, @Atif0604 The PR you have made is not proper. You have changed only one line of code. What I wanted is to completely re-modify that covid table(improvement in CSS) & improve live covid tracking functionality. Reply ASAP, if you are willing to do. Otherwise, we will give chance to others as well.

**Comment by Atif0604** [comment]
> Hey, @Atif0604 The PR you have made is not proper. You have changed only one line of code. What I wanted is to completely re-modify that covid table(improvement in CSS) & improve live covid tracking functionality. Reply ASAP, if you are willing to do. Otherwise, we will give chance to others as well.

Ok 
I will work the UI improvement of table

**Comment by skpandey885** [comment]
> > Hey, @Atif0604 The PR you have made is not proper. You have changed only one line of code. What I wanted is to completely re-modify that covid table(improvement in CSS) & improve live covid tracking functionality. Reply ASAP, if you are willing to do. Otherwise, we will give chance to others as well.
> 
> Ok I will work the UI improvement of table

@Atif0604 what is the update?

**Comment by Atif0604** [comment]
> > > Hey, @Atif0604 The PR you have made is not proper. You have changed only one line of code. What I wanted is to completely re-modify that covid table(improvement in CSS) & improve live covid tracking functionality. Reply ASAP, if you are willing to do. Otherwise, we will give chance to others as well.
> > 
> > 
> > Ok I will work the UI improvement of table
> 
> @Atif0604 what is the update?

I have already committed the new changes
