### ISSUE TITLE
Covid Page bugs

### ISSUE THREAD

**Issue by Shruti025** [skpandey885/HealhUb#92]
The Covid Page has certain responsiveness bugs. I am attaching certain screenshots.

The "Click me!" buttons are hiding for smaller screens
![image](https://user-images.githubusercontent.com/72005584/156307075-60f59e95-03bb-4e87-84f4-de1d38270e82.png)

The data is overflowing the container
![image](https://user-images.githubusercontent.com/72005584/156307212-c45fe6bc-7143-415a-8289-382cfff83bca.png)
![image](https://user-images.githubusercontent.com/72005584/156307246-5af244f1-42bc-4ee5-b8ae-4d1111ad7508.png)

The about section in the footer is not centered
![image](https://user-images.githubusercontent.com/72005584/156307306-60e93418-d43f-40f7-9b85-20e38cadbca7.png)

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by skpandey885** [comment]
Go ahead.
