### ISSUE TITLE
Add a Calorie Calculator to the tools Page

### ISSUE THREAD

**Issue by skpandey885** [skpandey885/HealhUb#95]
**CURRENT BEHAVIOUR:** The Tools Page has a dummy card at the Last.
<img width="579" alt="Screenshot 2022-03-03 at 1 04 33 PM" src="https://user-images.githubusercontent.com/78532081/156517863-8c245c4f-eb7a-48d5-b8fa-a2069491e366.png">

**EXPECTED BEHAVIOUR:** Make a Calorie Calculator Page and link the Dummy card to that page.
For Reference :  https://www.calculator.net/calorie-calculator.html

**Comment by mridul4101** [comment]
I would like to work under this issue for JWOC.
